insert into productos (id, nombre, descripcion, imagen, precio) values (NEXTVAL('hibernate_sequence'), ' AIR JORDAN 1 MID', 'En el camino hacia la grandeza. El clásico diseño de las AJ1 se renueva con toques de color innovadores y una combinación de materiales.', '../images/prod1.jpg', 129.99);
insert into productos (id, nombre, descripcion, imagen, precio) values (NEXTVAL('hibernate_sequence'), 'Jumpman Two Trey', 'Como "Two Trey" en la matrícula de MJ, hazte notar. Esta nueva generación de Jordan celebra la época de Mike en Chicago, con partes superiores de piel de alta calidad y suelas acolchadas Air.', '../images/prod2.jpg', 149.99);
insert into productos (id, nombre, descripcion, imagen, precio) values (NEXTVAL('hibernate_sequence'), 'Air Jordan 6 Retro', 'Las sextas zapatillas exclusivas de MJ se lanzaron durante la temporada 1990-1991, en la que "His Airness" se enfrentó a sus rivales para conseguir su primer campeonato. Ahora vuelven una gran variedad de esquemas de colores.', '../images/prod3.jpg', 199.99);
insert into productos (id, nombre, descripcion, imagen, precio) values (NEXTVAL('hibernate_sequence'), 'Air Jordan 7 Retro Q', 'Luce el estilo del 92 con esta última versión de las AJ7, que acerca el legado del campeonato a una nueva generación de coleccionistas de zapatillas. Has venido por el estilo retro y te quedarás por la confección premium y la exclusiva amortiguación Air.', '../images/prod4.jpg', 209.99);
insert into productos (id, nombre, descripcion, imagen, precio) values (NEXTVAL('hibernate_sequence'), 'Zion 2', 'Canaliza una combinación única de velocidad y potencia con unas zapatillas diseñadas para Zion y hechas para jugadores de cualquier nivel. La correa regulable de la parte superior mantiene el pie sujeto, al tiempo que la mediasuela firme te permite jugar ', '../images/prod5.jpg', 119.99);
insert into productos (id, nombre, descripcion, imagen, precio) values (NEXTVAL('hibernate_sequence'), 'Jordan Stay Loyal 2', 'Inspiradas en generaciones de Js, estas zapatillas son un collage de frescura. Los detalles de diseño recuperan décadas de zapatillas legendarias y rinden homenaje a la mítica carrera de MJ.', '../images/prod6.jpg', 119.99);

insert into usuarios (id, login, email, password) values (NEXTVAL('hibernate_sequence'), 'admin', 'admin@admin.com', '1234');
insert into usuarios (id, login, email, password) values (NEXTVAL('hibernate_sequence'), 'david', 'david@david.com', 'david');
insert into usuarios (id, login, email, password) values (NEXTVAL('hibernate_sequence'), 'eloi', 'eloi@eloi.com', 'eloi');